:toc:
= jQAssistant Test Impact Analysis Plugin

This project provides a http://jqassistant.org/[jQAssistant] plugin for dynamically generating test suites based on
changes in the version control system, i.e. Git.

The test suites are represented by files which can be passed as parameters to http://maven.apache.org/surefire/maven-surefire-plugin/[Maven Surefire Plugin]
or http://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin] via the `includesFile` option.

== Prerequisites

* Java 7 or higher
* Maven 3.2.5 or higher
* jQAssistant 1.3.0 or higher (see below)

== Building From Source

NOTE: This plugin has not been released yet, snapshots are available from https://oss.sonatype.org/content/repositories/snapshots[Sonatype OSS] snapshot repository.
Once the plugin has been released it will be published to http://search.maven.org[Maven Central].

Clone this repository and execute the following command:

----
mvn install
----

== Setup

The plugin can be enabled in a Maven based project by adding it as a dependency to the jQAssistant Maven plugin:

.pom.xml
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <version>1.3.0</version>
            <executions>
                <execution>
                    <id>default-cli</id>
                    <goals>
                        <goal>scan</goal>
                        <goal>analyze</goal>
                    </goals>
                    <configuration>
                        <failOnSeverity>MAJOR</failOnSeverity>
                        <warnOnSeverity>MINOR</warnOnSeverity>
                        <useExecutionRootAsProjectRoot>true</useExecutionRootAsProjectRoot>
                        <scanIncludes>
                            <scanInclude>
                                <path>${project.basedir}/.git</path>
                            </scanInclude>
                        </scanIncludes>
                        <reportProperties>                                               <!--1-->
                            <testimpactanalysis.report.directory>${session.executionRootDirectory}/target/testimpactanalysis</testimpactanalysis.report.directory>
                        </reportProperties>
                    </configuration>
                </execution>
            </executions>
            <dependencies>
                <dependency>                                                             <!--2-->
                    <groupId>org.jqassistant.contrib.testsuite</groupId>
                    <artifactId>jqassistant-test-impact-analysis-plugin</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
----
<1> Configures the directory where the jQAssistant testsuite plugin will create the files
<2> Declares the plugin as dependency for jQAssistant

Furthermore profiles should be defined for making execution easier:

[source,xml]
.pom.xml
----
<profiles>
    <profile>
        <id>create-commit-testsuite</id>                                                 <!--1-->
        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.buschmais.jqassistant</groupId>
                    <artifactId>jqassistant-maven-plugin</artifactId>
                    <configuration>
                        <concepts>
                            <concept>test-impact-analysis:SurefireSuiteForLastGitCommit</concept>   <!--2-->
                        </concepts>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </profile>

    <profile>
        <id>create-branch-testsuite</id>                                                 <!--3-->
        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.buschmais.jqassistant</groupId>
                    <artifactId>jqassistant-maven-plugin</artifactId>
                    <configuration>
                        <concepts>
                            <concept>test-impact-analysis:SurefireSuiteForCurrentBranch</concept>   <!--4-->
                        </concepts>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </profile>

    <profile>
        <id>run-testsuite</id>                                                           <!--5-->
        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <includesFile>${session.executionRootDirectory}/target/testimpactanalysis/${project.artifactId}</includesFile>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.buschmais.jqassistant</groupId>
                    <artifactId>jqassistant-maven-plugin</artifactId>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </profile>
</profile>
----
<1> Defines the profile to be used for creating a test suite based on the last Git commit
<2> Activates the concept `test-impact-analysis:SurefireSuiteForLastGitCommit`
<3> Defines the profile to be used for creating a test suite based on the commits within the current Git branch
<4> Activates the concept `test-impact-analysis:SurefireSuiteForCurrentBranch`
<5> Defines the profile for running the tests defined in the generated test suite

== Creating And Running A Test Suite

The profiles `create-commit-testsuite` and `create-branch-testsuite` are used to create the required test suite files.
Either one of the following commands needs to be executed:

[source,raw]
----
mvn clean verify -Pcreate-commit-testsuite
----

[source,raw]
----
mvn clean verify -Pcreate-branch-testsuite
----

The test suite files (one per artifact) are available in the 'target/testimpactanalysis' folder of the module where Maven has been executed, e.g.

[source,raw]
.target/testimpactanalysis/spring-petclinic
----
org/springframework/samples/petclinic/web/OwnerControllerTests.java
org/springframework/samples/petclinic/web/PetControllerTests.java
org/springframework/samples/petclinic/web/PetTypeFormatterTests.java
org/springframework/samples/petclinic/web/VetControllerTests.java
org/springframework/samples/petclinic/web/VisitControllerTests.java
----

The following command triggers a build which only executes the tests which are defined in the generated test suite files:

[source,raw]
----
mvn verify -Prun-testsuite
----

== Advanced: Selecting Specific Tests

It is possible to select only specific tests to be included in the created test suite files, e.g. if only integration tests shall be executed using the http://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin].
Therefore a rule needs to be created using Cypher (Neo4j query language) which does the required filtering.
The rule can be loaded by jQAssistant from Asciidoc or XML files located in the folder "jqassistant" in the root module of the Maven project:

.Example project structure
----
my-project/
          /jqassistant/my-rules.adoc
          /module1/pom.xml
          /module2/pom.xml
          /pom.xml
----

The following two rules select integration tests by checking their name for the suffix "IT":

.jqassistant/my-rules.adoc
....
= My Rules

[[my-rules:IntegrationTestsForLastGitCommit]]          // <1>
[source,cypher,role=concept,requiresConcepts="test-impact-analysis:TestsAffectedByLastGitCommit",reportType="surefire-suite"]
----
MATCH
  (artifact:Artifact)-[:CONTAINS]->(test:Affected:Test)
WHERE
  test.name ends with "IT"                             // <2>
RETURN
  artifact as Artifact, collect(test) as Tests
----

[[my-rules:IntegrationTestsForCurrentGitBranch]]       // <3>
[source,cypher,role=concept,requiresConcepts="test-impact-analysis:TestsAffectedByCurrentGitBranch",reportType="surefire-suite"]
----
MATCH
  (artifact:Artifact)-[:CONTAINS]->(test:Affected:Test)
WHERE
  test.name ends with "IT"
RETURN
  artifact as Artifact, collect(test) as Tests
----
....
<1> Declares the concept for integration tests affected by the last Git commit
<2> The filter clause for test classes having a name with the suffix "IT"
<3> Declares the concept for integration tests affected by commit within the current Git branch

The result of the concepts are reported as "surefire-suite".
This report type requires each row to provide two columns:

Artifact::
  The artifact where affected test classes are located.
Tests::
  The collection of affected tests for the artifact.

== Feedback

Please report any issues https://github.com/jqassistant-contrib/jqassistant-test-impact-analysis-plugin/issues[here].
